### ISSUE TITLE
请问还在更新吗

### ISSUE THREAD

**Issue by zhjue** [SuperNG6/docker-qbittorrent#11]
看dockerhub上到4.3.3不动了, 但是changelogs里写了已经出了4.3.5和4.3.6

**Comment by SuperNG6** [comment]
最近工作忙，没时间更新，近期更新

**Comment by SuperNG6** [comment]
已更新
![4KyXbz](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/4KyXbz.png)
