### ISSUE TITLE
webUI设置成简体中文显示的是英文

### ISSUE THREAD

**Issue by a492219408** [SuperNG6/docker-qbittorrent#19]
<img width="1026" alt="Snipaste_2022-12-03_21-22-25" src="https://user-images.githubusercontent.com/69742931/205442935-5761352e-52d8-4055-b167-f5c530aa529e.png">
设置成繁体是正常显示的，但设置成简体中文就显示英文，浏览器禁用了缓存还是一样

**Comment by a492219408** [comment]
容器初始化后用文本编辑器把`/config/qBittorrent.conf`里的
```
[Preferences]
General\Locale=zh
```
改成
```
[Preferences]
General\Locale=zh_CN
```
解决了这个问题，可能是程序写配置的时候弄错了吧，希望开发者可以修复一下这个问题

**Comment by SuperNG6** [comment]
> 容器初始化后用文本编辑器把`/config/qBittorrent.conf`里的
> 
> ```
> [Preferences]
> General\Locale=zh
> ```
> 
> 改成
> 
> ```
> [Preferences]
> General\Locale=zh_CN
> ```
> 
> 解决了这个问题，可能是程序写配置的时候弄错了吧，希望开发者可以修复一下这个问题

已修复
这个配置是根据官方配置文件修改精简的（其他配置，QB会自动生成），4.5之前是正常的。
