### ISSUE TITLE
最新版 latest 不能设置中文

### ISSUE THREAD

**Issue by 91270** [SuperNG6/docker-qbittorrent#20]
本身安装完之后显示的是中文，但是一保存设置，就会变成英文

**Comment by meiotoha** [comment]
在webui中选择`简体中文`保存后， `qBittorrent.conf`里会变成`General\Locale=zh`,手动改回`General\Locale=zh_CN`恢复简体中文界面

**Comment by dongqiceo** [comment]
> 在webui中选择`简体中文`保存后， `qBittorrent.conf`里会变成`General\Locale=zh`,手动改回`General\Locale=zh_CN`恢复简体中文界面。 [userdocs/qbittorrent-nox-static#104](https://github.com/userdocs/qbittorrent-nox-static/issues/104)

非常感谢，知道是小bug，用了几天繁体

**Comment by 362227** [comment]
> 在webui中选择`简体中文`保存后， `qBittorrent.conf`里会变成`General\Locale=zh`,手动改回`General\Locale=zh_CN`恢复简体中文界面。 [userdocs/qbittorrent-nox-static#104](https://github.com/userdocs/qbittorrent-nox-static/issues/104)

我改了也没用，重启一下又是General\Locale=zh
