### ISSUE TITLE
求教外网401"unauthorized"如何处理？

### ISSUE THREAD

**Issue by bendusy** [SuperNG6/docker-qbittorrent#6]
内网访问ip：8080可以正常使用；
外网域名：8081无法使用，已尝试更换端口；
其他emby等服务正常

**Comment by SuperNG6** [comment]
QB设置里修改端口，内外网用一样的端口

**Comment by lianyanjiajia** [comment]
更新之后我也提示unauthorized 纯内网 之前没有这个问题 我是truenas scale不能用8080

**Comment by SuperNG6** [comment]
这篇帖子评论区有说明
https://sleele.com/2020/04/09/docker-qbittorrent-optimizing/#comment-1437-image
![](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/2021-02-02/CIwC4l.png)

**Comment by lianyanjiajia** [comment]
> 

我在config文件里 加上了这条 但现在每次必须回车一下才能访问
